### ISSUE TITLE
Publish v0.3 to NPM

### ISSUE THREAD

**Issue by pwalsh** [okfn/datapackage-validate#8]
Done, and ready to publish:

* Changes merged: https://github.com/okfn/datapackage-validate/pull/7 
* Docs updated: https://github.com/okfn/datapackage-validate

**Comment by rgrp** [comment]
@pwalsh i'd like to make you an owner / publisher with me of the package (and gvidon too). Can you let me know your username. I also would suggest we request to sysadmin the creation of a generic OK user on npm and we auto add that user to published packages as a co-owner (do you want to lead on taht request?)

**Comment by pwalsh** [comment]
I'm pwalsh on npm, and Artem is nide. I also have created the OK user myself after discussing with sysadmin - the user is okfn

**Comment by rgrp** [comment]
@pwalsh you and okfn user are now owners. I'll let you add artem if you want to.
